### ISSUE TITLE
Dependency missing

### ISSUE THREAD

**Issue by WGierke** [Steppschuh/SlackMessageBuilder#1]
I got a "java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/gson/GsonBuilder;" so perhaps you could mention somewhere that Gson is required?

**Comment by Steppschuh** [comment]
Hey,
the serialization of messages depends on [Gson](https://github.com/google/gson). I forgot to mention that, it's now added in the project [readme](https://github.com/Steppschuh/SlackMessageBuilder/blob/master/README.md).
